[tool.ruff]
line-length = 100

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
exclude = [
	"pongus_magnificus/dashboard/*",
	"pongus_magnificus/quiz/*",
	"**/migrations/*",
]

[tool.ruff.lint.per-file-ignores]
"pongus_magnificus/transcendence/settings.py" = ["E402"]
"pongus_magnificus/transcendence/asgi.py" = ["E402"]
"**/migrations/*" = ["ALL"]  # Ignore all ruff rules for migration files