[tool.ruff]
line-length = 100
[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
[tool.ruff.lint.per-file-ignores]
"backend/users/views.py" = ["F841"]
"backend/transcendence/settings.py" = ["E402"]
"**/migrations/*" = ["ALL"]  # Ignore all ruff rules for migration files