# Generated by Django 5.1.4 on 2025-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournement_game_id',
            field=models.IntegerField(default=0),
        ),
    ]
