# Generated by Django 5.1.4 on 2025-01-14 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_tournement_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_created', to='game.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments_participated', to='game.player'),
        ),
    ]
