# Generated by Django 5.1.4 on 2025-01-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_tournament_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_created', to='game.player'),
        ),
    ]
