# Generated by Django 5.1.4 on 2025-01-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_tournament_players_alter_tournament_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
    ]
