# Generated by Django 5.1.5 on 2025-01-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='game', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
